name: 🧲 Model Torrent Submission
description: Submit a quantized AI model torrent to Qal.to
title: "[MODEL] "
labels: ["model-submission", "pending-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## Submit a Model Torrent

        Thank you for contributing to Qal.to! Please fill out the information below.

        **Requirements:**
        - Model must be in GGUF format
        - You must have the right to distribute
        - You must commit to seeding for 30+ days
        - New uploaders go through verification

  - type: input
    id: model_name
    attributes:
      label: Model Name
      description: Full model name including quantization
      placeholder: "e.g., Llama 3.3 70B Instruct Q4_K_M"
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organization/Creator
      placeholder: "e.g., Meta, Mistral, TheBloke"

  - type: input
    id: parameters
    attributes:
      label: Parameters
      placeholder: "e.g., 70.5B, 7B, 405B"

  - type: dropdown
    id: quantization
    attributes:
      label: Quantization Level
      options:
        - Q2_K
        - Q3_K_S
        - Q3_K_M
        - Q3_K_L
        - Q4_K_S
        - Q4_K_M
        - Q4_K_L
        - Q5_K_S
        - Q5_K_M
        - Q6_K
        - Q8_0
        - FP16
    validations:
      required: true

  - type: input
    id: file_size
    attributes:
      label: File Size (GB)
      placeholder: "e.g., 40.5"
    validations:
      required: true

  - type: checkboxes
    id: tags
    attributes:
      label: Tags
      description: Select all that apply
      options:
        - label: Chat
        - label: Code
        - label: Reasoning
        - label: Vision
        - label: Instruct
        - label: Base Model

  - type: textarea
    id: magnet_link
    attributes:
      label: Magnet Link
      description: Full magnet URI with trackers
      placeholder: "magnet:?xt=urn:btih:..."
    validations:
      required: true

  - type: input
    id: info_hash
    attributes:
      label: Info Hash
      description: Optional - will be extracted from magnet link
      placeholder: "c12fe1c06bba254a9dc9f519b335aa7c1367a88a"

  - type: input
    id: sha256
    attributes:
      label: SHA256 Checksum
      description: Run `sha256sum model.gguf` to get this
      placeholder: "a1b2c3d4e5f6..."
    validations:
      required: true

  - type: input
    id: source_url
    attributes:
      label: Source URL
      description: HuggingFace or original source
      placeholder: "https://huggingface.co/..."

  - type: textarea
    id: description
    attributes:
      label: Model Description
      description: Capabilities, benchmarks, usage notes
      placeholder: |
        ## About This Model

        This model is...

        ## Performance
        - Benchmark results...

        ## Usage
        ```bash
        llama-cli -m model.gguf -p "Hello"
        ```

  - type: input
    id: uploader_name
    attributes:
      label: Your Username
      placeholder: "YourGitHubUsername"
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Contact Email
      description: For verification (not displayed publicly)
      placeholder: "you@example.com"
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmations
      options:
        - label: I commit to seeding this torrent for at least 30 days
          required: true
        - label: I confirm I have the right to distribute this model
          required: true
        - label: I have verified the SHA256 checksum matches the source
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ### What happens next?

        1. **New uploaders:** Your submission will be reviewed within 24-48 hours
        2. **Trusted uploaders:** Your submission will be published immediately
        3. We will verify the checksum and test the torrent
        4. Once approved, your model will appear on Qal.to

        ### How to create a torrent

        ```bash
        # Using transmission-cli
        transmission-create \
          --tracker udp://tracker.opentrackr.org:1337/announce \
          --tracker udp://open.stealth.si:80/announce \
          --comment "Model description" \
          --output model.torrent \
          model.gguf

        # Get magnet link
        transmission-show model.torrent | grep "Magnet:"
        ```

        Thank you for contributing to open AI!
